### ISSUE TITLE
Редактирование ябла с клавиатуры

### ISSUE THREAD

**Issue by chestozo** [Katochimoto/x-bubbles#2]
Сейчас с клавиатуры можно перейти на яббл, но нельзя начать его редактировать.
Кажется, можно добавить такую возможность, к примеру, по пробелу (лучше конечно иметь возможность указать свой шорткат).

**Comment by Katochimoto** [comment]
https://github.com/Katochimoto/x-bubbles/commit/13486818b985395445d97e495f3d77f4147077d7

по пробелу и по Enter, если выбран 1 бабл
