### ISSUE TITLE
Доработки функциональности

### ISSUE THREAD

**Issue by bt4R9** [Katochimoto/x-bubbles#6]
Для использования в мобильных браузерах в React приложениях нужны следующие доработки:
- Отключаемый режим выделения. На мобильных устройствах, как правило, нет стрелочек на клавиатуре, и возможность ходить по бабблам поэтому просто не нужна.
- Удаление баббла по нажатию Backspace. Сделать реально, достаточно смотреть на `target.previousSibling`.
- Событие перед удалением баббла. Без такого события непонятно как делать unmount компонент.

**Comment by Katochimoto** [comment]
готово
https://github.com/Katochimoto/x-bubbles/pull/7

**Comment by Katochimoto** [comment]
в релизе 1.0.0
