### ISSUE TITLE
Добавить событие ready для определения готовности работы с элементом

### ISSUE THREAD

**Issue by Katochimoto** [Katochimoto/x-bubbles#8]
Обработчик выполняется сразу после добавления, если событие `ready` наступило.

http://webcomponents.org/polyfills/custom-elements/#polyfill-notes

**Comment by bt4R9** [comment]
👍

**Comment by Katochimoto** [comment]
готово
https://github.com/Katochimoto/x-bubbles/pull/7

```
setNode.ready(function () { /*...*/ })

**Comment by Katochimoto** [comment]
в релизе
https://github.com/Katochimoto/x-bubbles/releases/tag/1.0.0

**Comment by bt4R9** [comment]
Получилось странно, метод `ready` становится доступным после инициализации кастомных элементов, а до этого undefined. :D

**Comment by bt4R9** [comment]
@Katochimoto

**Comment by Katochimoto** [comment]
сорян, косячина, не подумал
придется событием на window обрабатывать

**Comment by Katochimoto** [comment]
сделаю тротлинг инииализации компонент до срабатывания микротасков
компоненты, которые заинитились , будут прокинуты массивом в данные события
событие будет на window не баблиться и не отменяться
событие будет называться `x-bubbles-ready`

**Comment by Katochimoto** [comment]
по факту нужно только первое срабатывание
если его достаточно, то подписываемся через once

**Comment by Katochimoto** [comment]
https://github.com/Katochimoto/x-bubbles/releases/tag/1.0.2
